# Project information
site_name: Markdown test
# defeine TOC or order of website-
nav:
  - Home: index.md

site_author: Ramiz moktader
site_description: >-
  DESCRIPTION

# Repository
repo_name: ramiz-moktader/
repo_url: https://github.com/ramiz-moktader/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ramiz-moktader/
    - icon: fontawesome/brands/twitter
      link: https://github.com/ramiz-moktader/
    - icon: fontawesome/brands/linkedin
      link: https://github.com/ramiz-moktader/
    - icon: fontawesome/brands/instagram
      link: https://github.com/ramiz-moktader/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search
extra:
  generator: false
copyright: |
  &copy; 2022 <a href="https://github.com/ramiz-moktader/"  target="_blank" rel="noopener"> Ramiz moktader</a>