# Project information
site_name: Intro to programming
site_url: https://geocodinglab.com
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Cohort-2: cohort-2.md
  - Certificate Verification: certificates/index.md
  - Shapefiles & Datasets: shapeFiles.md
  - Pre programming Basic: pre-prog-basic.md
  - Intro to programming with JavaScript:
        - Class 1 - var, data type, comparison operator: intro-to-programming-with-js-class1.md
        - Class 2 - Arithmetic operators, conditional statements: conditional-statements-class2.md
        - Class 3 - Logical operator, loop: logical-operator-loop-class3.md 
        - Class 4 - Array: array-class4.md
        - Class 5 - Function: function-class5.md
        - Class 6 - Object: js-objects-class6.md 
  - Intro to GIS and GEE: 
     - Class 7 - Basic structure of an image: image-formation-class7.md
     - Class 8 - GIS data type and vector data in GEE: raster-vector-data-in-gee.md
     - Class 9 - GEE client VS Server: gee-client-server-side-class9.md
     - Class 10 - GEE image collection: imgcollection-class10.md
     - Class 11 - Indices calculation from imagery: indexCalculationClass11.md
     - Class 12 - Value thresholding and area calculation : mapThreasholdingclass12.md
     - Class 13 - Group Reducer and Zonal statistics  : groupReducerClass13.md
     - Class 14 - Exporting raster and vector data : exportingDataClass14.md
     - Class 15 - Supervised and unSupervised Machine learning : supmlclass15.md


site_author: GEOCODING LAB 
site_description: Geospatial Programming and Cloud Earth Engine course materials in Bengali by GEOCODING LAB.

# Repository
repo_name: ramiz-moktader/geospatial-programming-course
repo_url: https://github.com/ramiz-moktader/geospatial-programming-course

# Configuration
theme:
  name: material         
  logo: images/logo-jpg.jpg
  favicon: images/logo.png
  features:
    - content.code.copy
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ramiz-moktader/geospatial-programming-course
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/groups/902693884377077 
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@geocodinglab

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - toc:
      permalink: true
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/extra.css
  
plugins:
  - search
  - mkdocs-video
copyright: |
  &copy; 2026 GEO-CODING LAB